#Python program to perform basic arithmetic operations by taking input from the user. 
a = int(input("enter a:"))
b = int(input("enter b:"))
print("sum=", a+b,"\n")
a = float(input("enter a:"))
b = float(input("enter b:"))
print("diff=",a-b,"\n")
a = int(input("enter a:"))
b = int(input("enter b:"))
print("multiply=",a*b,"\n")
a = float(input("enter a:"))
b = float(input("enter b:"))
print("divison=",a/b,"\n")
a = int(input("enter a:"))
b = int(input("enter b:"))
print("module=",a%b)
