file = open("student.txt","w")
file.write("Name:Ankit Pal\n")
file.write("Course:BE(CSE)\n")
file.write("Duration:Four Years\n")
file.close()
file = open("student.txt","r")
print("file contents:")
print(file.read())
file.close()
file = open("student.txt","a")
file.write("College:Dbrau Agra\n")
file.close()
file = open("student.txt","r")
print("Updated File Contents:")
print(file.read())
file.close()